# Generated by Django 5.2.5 on 2025-08-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telepon', models.CharField(blank=True, max_length=20, null=True)),
                ('total_pesanan', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('menunggu', 'Menunggu'), ('nonaktif', 'Nonaktif')], default='menunggu', max_length=10)),
            ],
        ),
    ]
